# Naver News 크롤링 + TFIDF 분석 실습

### source
- https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=105&oid=018&aid=0004430108
- https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=014&aid=0004424362
- https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=101&oid=001&aid=0011614790
- https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=101&oid=119&aid=0002402191

In [1]:
from bs4 import BeautifulSoup
import requests
import re

In [8]:
url = 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=105&oid=018&aid=0004430108'
headers = {"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"}
response = requests.get(url, headers=headers)
soup = BeautifulSoup(response.text, 'html.parser')

In [113]:
soup.select('title')

In [114]:
soup.select('div._article_body_contents')

[<div class="_article_body_contents" id="articleBodyContents">
 <!-- 본문 내용 -->
 <!-- TV플레이어 -->
 <!-- // TV플레이어 -->
 <script type="text/javascript">
 // flash 오류를 우회하기 위한 함수 추가
 function _flash_removeCallback() {}
 </script>
 <strong class="media_end_summary">과기정통부, 22일 유영민 장관 등 참석해 기념행사<br/>2021년까지 1516억원 투입, 5100여종 데이터 구축<br/>민간 클라우드 통한 외부연계체계도.."개방성 강화"</strong>[이데일리 이재운 기자] 국가 차원의 빅데이터 활용 시대가 열린다. 새로운 산업 창출과 기존 산업의 변화에 이르는 ‘혁신성장’을 위한 센터가 문을 연다. 10개 분야에 걸쳐 ‘데이터 경제’의 발전을 위한 정부의 청사진을 현실로 구현하는데 앞장선다는 계획이다.<br/><br/>22일 과학기술정보통신부는 서울 중구 대한상공회의소에서 데이터 생태계 조성과 혁신 성장의 기반 마련을 위한 ‘빅데이터 플랫폼 및 센터’ 출범식 행사를 개최했다. 유영민 과기정통부 장관을 비롯해 노웅래 국회 과학기술정보방송통신위원회 위원장 등 300여명이 참가했다.<br/><br/><strong>◇10개 분야 100개 센터..3년간 1516억원 투입<br/><br/><table align="CENTER" bgcolor="ffffff" border="0" cellpadding="0" cellspacing="5" width="466"><tr><td bgcolor="ffffff" style="PADDING-RIGHT: 2px; PADDING-LEFT: 2px; PADDING-BOTTOM: 2px; PADDING-TOP: 2px;"><table bgcolor="ffffff" border="0" cellpadding="0" cellspacing="5"><tr><td><span class="end_photo_org"><img alt="" src="https://imgnews.pstatic.net/image/018/2019/07/22/0004430108_001_20190722152006062.jpg?type=w647"/></span></td></tr><tr><td style="PADDING-BOTTOM: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT-FAMILY: 돋움,돋움체; COLOR: 595959; FONT-SIZE: 9pt; PADDING-TOP: 2px;">이미지: 픽사베이</td></tr></table></td></tr></table></strong><br/><br/>빅데이터는 데이터 활용을 통해 혁신성장을 이루자는 문재인 정부의 경제 성장 핵심 요소중 하나다. 문재인 대통령이 직접 올 들어 데이터 활용과 이에 따른 정보보호(보안)에 대한 중요성을 강조하기도 했다.<br/><br/>이런 맥락 속에서 빅데이터센터는 공공과 민간이 협업해 활용도 높은 양질의 데이터를 생산·구축하고, 플랫폼은 이를 수집·분석·유통하는 역할을 담당한다. 과기정통부는 분야별 플랫폼 10개소와 이와 연계된 기관별 센터 100개소를 구축하는데 3년간 총 1516억원을 투입할 계획이며, 올해 우선 640억원 규모의 사업을 추진하고 있다.<br/><br/>대상 분야는 △금융(BC카드) △환경(한국수자원공사) △문화(한국문화정보원) △교통(한국교통연구원) △헬스케어(국립암센터) △유통·소비(매일방송) △통신(KT) △중소기업(더존비즈온) △지역경제(경기도청) △산림(한국임업진흥원) 등으로 현재 1차 공모를 통해 72개 빅데이터 센터를 선정했고, 다음달 8일까지 2차 공모를 통해 28개를 추가 선정해 총 100개를 지원, 운영할 계획이다. 이를 통해 데이터 생태계를 혁신하고 기업의 경쟁력을 제고하는 역할을 수행한다.<br/><br/>주요 활용 전략·사례를 보면 빅데이터 활용을 통해 ‘신(新) 시장’을 창출하는 방안을 담고 있다. 금융 플랫폼의 경우 소상공인 신용평가 고도화 등을 통해 금융 취약 계층 대상 중금리 대출이자를 2%p 절감해 연간 1조원의 신규대출을 창출할 전망이다. 유통·소비와 중소기업 플랫폼은 소상공인이나 중소기업의 폐업률 감소를, 문화 플랫폼은 문화·예술 관람률과 생활체육 참여율을 높이는 방안을 모색한다. 의료비 절감(헬스케어)과 기업의 매출 향상을 통한 산업 육성(통신·산림) 등도 눈길을 끈다.<br/><br/><table align="CENTER" bgcolor="ffffff" border="0" cellpadding="0" cellspacing="5" width="500"><tr><td bgcolor="ffffff" style="PADDING-RIGHT: 2px; PADDING-LEFT: 2px; PADDING-BOTTOM: 2px; PADDING-TOP: 2px;"><table bgcolor="ffffff" border="0" cellpadding="0" cellspacing="5"><tr><td><span class="end_photo_org"><img alt="" src="https://imgnews.pstatic.net/image/018/2019/07/22/0004430108_002_20190722152006078.jpg?type=w647"/></span></td></tr><tr><td style="PADDING-BOTTOM: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT-FAMILY: 돋움,돋움체; COLOR: 595959; FONT-SIZE: 9pt; PADDING-TOP: 2px;">과기정통부 제공</td></tr></table></td></tr></table><strong>◇2021년까지 5100여종 데이터 구축..AI 알고리즘 제공도<br/><br/></strong>센터는 우선 분야별 데이터 부족 문제를 해소하기 위해 올해 말까지 시장 수요가 높은 1400여종 신규 데이터를 생산ㆍ구축하고, 사업이 완료되는 2021년까지 총 5100여종 양질의 풍부한 데이터를 생산·구축해 시장에 공급할 계획이다.<br/><br/>특히 공공과 민간 사이 데이터 파일형식 등이 달라 호환이 제대로 이뤄지지 못한 문제를 해소하기 위해 개방형 표준을 적용하고, 품질관리기준도 마련해 운영한다.<br/><br/>기업들이 실제 활용 가능한 최신 데이터를 확보하는데도 수개월이 소요된다는 문제점을 개선하기 위한 방안도 추진한다. 센터와 플랫폼 간 연계체계에는 민간 클라우드를 기반으로 활용하고, 센터에 축적된 데이터도 계속 외부와 개방·공유하며 최신·연속성을 확보한다는 계획이다.<br/><br/>100개 센터에서 수집된 데이터를 융합·분석한 뒤 맞춤형 데이터 제작 등 양질의 데이터로 재생산하고, 기업들이 필요로 하는 데이터를 원하는 형태로 즉시 활용할 수 있도록 제공할 계획이다. 다양한 분석 도구는 물론 인공지능(AI) 학습 알고리즘도 제공해 이용자가 보다 사용하기 편리한 환경을 제공한다.<br/><br/>이밖에 필요한 데이터를 쉽게 등록하고 검색할 수 있도록 기준을 마련하고, 데이터 보유와 관리에 대한 체계(거버넌스)를 논의하는 ‘데이터 얼라이언스’를 구성해 보다 안전하게 이용하는 방안도 마련했다.<br/><br/>유영민 과기정통부 장관은 “오늘 출범식은 대한민국이 데이터 강국으로 가기 위한 초석을 놓은 자리”라며 “세계 주요국들보다 데이터 경제로 나아가는 발걸음이 다소 늦었지만, 빅데이터 플랫폼과 센터를 지렛대로 우리나라의 낙후된 데이터 생태계를 혁신하고 기업의 경쟁력을 한 단계 제고할 수 있도록 정책적 역량을 집중하겠다”고 밝혔다.<br/><br/>이재운 (jwlee@edaily.co.kr)<br/><br/>네이버 홈에서 ‘이데일리’ 뉴스 <a href="http://media.naver.com/channel/promotion.nhn?oid=018" target="_blank"><b><font color="f98b10">[구독하기▶]</font></b></a><br/>꿀잼가득 <a href="https://tv.naver.com/edaily/" target="_blank"><b><font color="f98b10">[영상보기▶]</font></b></a> , 청춘뉘우스~ <a href="http://snaptime.edaily.co.kr/" target="_blank"><b><font color="f98b10">[스냅타임▶]</font></b></a><br/><br/><p><br/>＜ⓒ종합 경제정보 미디어 이데일리 - 무단전재 &amp; 재배포 금지＞</p>
 <!-- // 본문 내용 -->
 </div>]

In [143]:
news = soup.select('div._article_body_contents')[0].text

In [144]:
news = news.split('_flash_removeCallback')[1]
news = news.split('네이버 홈에서')[0]

In [146]:
email_ptn = '[a-zA-Z0-9_\-.]+@[a-z]+(?:\.[a-z]+)+'
news = re.split(email_ptn, news)[0]

In [147]:
news

'() {}\n\n과기정통부, 22일 유영민 장관 등 참석해 기념행사2021년까지 1516억원 투입, 5100여종 데이터 구축민간 클라우드 통한 외부연계체계도.."개방성 강화"[이데일리 이재운 기자] 국가 차원의 빅데이터 활용 시대가 열린다. 새로운 산업 창출과 기존 산업의 변화에 이르는 ‘혁신성장’을 위한 센터가 문을 연다. 10개 분야에 걸쳐 ‘데이터 경제’의 발전을 위한 정부의 청사진을 현실로 구현하는데 앞장선다는 계획이다.22일 과학기술정보통신부는 서울 중구 대한상공회의소에서 데이터 생태계 조성과 혁신 성장의 기반 마련을 위한 ‘빅데이터 플랫폼 및 센터’ 출범식 행사를 개최했다. 유영민 과기정통부 장관을 비롯해 노웅래 국회 과학기술정보방송통신위원회 위원장 등 300여명이 참가했다.◇10개 분야 100개 센터..3년간 1516억원 투입이미지: 픽사베이빅데이터는 데이터 활용을 통해 혁신성장을 이루자는 문재인 정부의 경제 성장 핵심 요소중 하나다. 문재인 대통령이 직접 올 들어 데이터 활용과 이에 따른 정보보호(보안)에 대한 중요성을 강조하기도 했다.이런 맥락 속에서 빅데이터센터는 공공과 민간이 협업해 활용도 높은 양질의 데이터를 생산·구축하고, 플랫폼은 이를 수집·분석·유통하는 역할을 담당한다. 과기정통부는 분야별 플랫폼 10개소와 이와 연계된 기관별 센터 100개소를 구축하는데 3년간 총 1516억원을 투입할 계획이며, 올해 우선 640억원 규모의 사업을 추진하고 있다.대상 분야는 △금융(BC카드) △환경(한국수자원공사) △문화(한국문화정보원) △교통(한국교통연구원) △헬스케어(국립암센터) △유통·소비(매일방송) △통신(KT) △중소기업(더존비즈온) △지역경제(경기도청) △산림(한국임업진흥원) 등으로 현재 1차 공모를 통해 72개 빅데이터 센터를 선정했고, 다음달 8일까지 2차 공모를 통해 28개를 추가 선정해 총 100개를 지원, 운영할 계획이다. 이를 통해 데이터 생태계를 혁신하고 기업의 경쟁력을 제고하는 역할을 수행한다.주요 활용 전략·사례를 보면 빅데이터 활용을 통해 ‘신(新) 시장’을 창출하는 방안을 담고 있다. 금융 플랫폼의 경우 소상공인 신용평가 고도화 등을 통해 금융 취약 계층 대상 중금리 대출이자를 2%p 절감해 연간 1조원의 신규대출을 창출할 전망이다. 유통·소비와 중소기업 플랫폼은 소상공인이나 중소기업의 폐업률 감소를, 문화 플랫폼은 문화·예술 관람률과 생활체육 참여율을 높이는 방안을 모색한다. 의료비 절감(헬스케어)과 기업의 매출 향상을 통한 산업 육성(통신·산림) 등도 눈길을 끈다.과기정통부 제공◇2021년까지 5100여종 데이터 구축..AI 알고리즘 제공도센터는 우선 분야별 데이터 부족 문제를 해소하기 위해 올해 말까지 시장 수요가 높은 1400여종 신규 데이터를 생산ㆍ구축하고, 사업이 완료되는 2021년까지 총 5100여종 양질의 풍부한 데이터를 생산·구축해 시장에 공급할 계획이다.특히 공공과 민간 사이 데이터 파일형식 등이 달라 호환이 제대로 이뤄지지 못한 문제를 해소하기 위해 개방형 표준을 적용하고, 품질관리기준도 마련해 운영한다.기업들이 실제 활용 가능한 최신 데이터를 확보하는데도 수개월이 소요된다는 문제점을 개선하기 위한 방안도 추진한다. 센터와 플랫폼 간 연계체계에는 민간 클라우드를 기반으로 활용하고, 센터에 축적된 데이터도 계속 외부와 개방·공유하며 최신·연속성을 확보한다는 계획이다.100개 센터에서 수집된 데이터를 융합·분석한 뒤 맞춤형 데이터 제작 등 양질의 데이터로 재생산하고, 기업들이 필요로 하는 데이터를 원하는 형태로 즉시 활용할 수 있도록 제공할 계획이다. 다양한 분석 도구는 물론 인공지능(AI) 학습 알고리즘도 제공해 이용자가 보다 사용하기 편리한 환경을 제공한다.이밖에 필요한 데이터를 쉽게 등록하고 검색할 수 있도록 기준을 마련하고, 데이터 보유와 관리에 대한 체계(거버넌스)를 논의하는 ‘데이터 얼라이언스’를 구성해 보다 안전하게 이용하는 방안도 마련했다.유영민 과기정통부 장관은 “오늘 출범식은 대한민국이 데이터 강국으로 가기 위한 초석을 놓은 자리”라며 “세계 주요국들보다 데이터 경제로 나아가는 발걸음이 다소 늦었지만, 빅데이터 플랫폼과 센터를 지렛대로 우리나라의 낙후된 데이터 생태계를 혁신하고 기업의 경쟁력을 한 단계 제고할 수 있도록 정책적 역량을 집중하겠다”고 밝혔다.이재운 ('

In [148]:
news_re = re.sub("[^가-힣a-zA-Z0-9@.%]", " ", news)

In [149]:
news_re

'       과기정통부  22일 유영민 장관 등 참석해 기념행사2021년까지 1516억원 투입  5100여종 데이터 구축민간 클라우드 통한 외부연계체계도.. 개방성 강화  이데일리 이재운 기자  국가 차원의 빅데이터 활용 시대가 열린다. 새로운 산업 창출과 기존 산업의 변화에 이르는  혁신성장 을 위한 센터가 문을 연다. 10개 분야에 걸쳐  데이터 경제 의 발전을 위한 정부의 청사진을 현실로 구현하는데 앞장선다는 계획이다.22일 과학기술정보통신부는 서울 중구 대한상공회의소에서 데이터 생태계 조성과 혁신 성장의 기반 마련을 위한  빅데이터 플랫폼 및 센터  출범식 행사를 개최했다. 유영민 과기정통부 장관을 비롯해 노웅래 국회 과학기술정보방송통신위원회 위원장 등 300여명이 참가했다. 10개 분야 100개 센터..3년간 1516억원 투입이미지  픽사베이빅데이터는 데이터 활용을 통해 혁신성장을 이루자는 문재인 정부의 경제 성장 핵심 요소중 하나다. 문재인 대통령이 직접 올 들어 데이터 활용과 이에 따른 정보보호 보안 에 대한 중요성을 강조하기도 했다.이런 맥락 속에서 빅데이터센터는 공공과 민간이 협업해 활용도 높은 양질의 데이터를 생산 구축하고  플랫폼은 이를 수집 분석 유통하는 역할을 담당한다. 과기정통부는 분야별 플랫폼 10개소와 이와 연계된 기관별 센터 100개소를 구축하는데 3년간 총 1516억원을 투입할 계획이며  올해 우선 640억원 규모의 사업을 추진하고 있다.대상 분야는  금융 BC카드   환경 한국수자원공사   문화 한국문화정보원   교통 한국교통연구원   헬스케어 국립암센터   유통 소비 매일방송   통신 KT   중소기업 더존비즈온   지역경제 경기도청   산림 한국임업진흥원  등으로 현재 1차 공모를 통해 72개 빅데이터 센터를 선정했고  다음달 8일까지 2차 공모를 통해 28개를 추가 선정해 총 100개를 지원  운영할 계획이다. 이를 통해 데이터 생태계를 혁신하고 기업의 경쟁력을 제고하는 역할을 수행한다.주요 활용 전략 사례를 보면 빅데이터 활용을 통해  신    시장 을 창출하는 방안을 담고 있다. 금융 플랫폼의 경우 소상공인 신용평가 고도화 등을 통해 금융 취약 계층 대상 중금리 대출이자를 2%p 절감해 연간 1조원의 신규대출을 창출할 전망이다. 유통 소비와 중소기업 플랫폼은 소상공인이나 중소기업의 폐업률 감소를  문화 플랫폼은 문화 예술 관람률과 생활체육 참여율을 높이는 방안을 모색한다. 의료비 절감 헬스케어 과 기업의 매출 향상을 통한 산업 육성 통신 산림  등도 눈길을 끈다.과기정통부 제공 2021년까지 5100여종 데이터 구축..AI 알고리즘 제공도센터는 우선 분야별 데이터 부족 문제를 해소하기 위해 올해 말까지 시장 수요가 높은 1400여종 신규 데이터를 생산 구축하고  사업이 완료되는 2021년까지 총 5100여종 양질의 풍부한 데이터를 생산 구축해 시장에 공급할 계획이다.특히 공공과 민간 사이 데이터 파일형식 등이 달라 호환이 제대로 이뤄지지 못한 문제를 해소하기 위해 개방형 표준을 적용하고  품질관리기준도 마련해 운영한다.기업들이 실제 활용 가능한 최신 데이터를 확보하는데도 수개월이 소요된다는 문제점을 개선하기 위한 방안도 추진한다. 센터와 플랫폼 간 연계체계에는 민간 클라우드를 기반으로 활용하고  센터에 축적된 데이터도 계속 외부와 개방 공유하며 최신 연속성을 확보한다는 계획이다.100개 센터에서 수집된 데이터를 융합 분석한 뒤 맞춤형 데이터 제작 등 양질의 데이터로 재생산하고  기업들이 필요로 하는 데이터를 원하는 형태로 즉시 활용할 수 있도록 제공할 계획이다. 다양한 분석 도구는 물론 인공지능 AI  학습 알고리즘도 제공해 이용자가 보다 사용하기 편리한 환경을 제공한다.이밖에 필요한 데이터를 쉽게 등록하고 검색할 수 있도록 기준을 마련하고  데이터 보유와 관리에 대한 체계 거버넌스 를 논의하는  데이터 얼라이언스 를 구성해 보다 안전하게 이용하는 방안도 마련했다.유영민 과기정통부 장관은  오늘 출범식은 대한민국이 데이터 강국으로 가기 위한 초석을 놓은 자리 라며  세계 주요국들보다 데이터 경제로 나아가는 발걸음이 다소 늦었지만  빅데이터 플랫폼과 센터를 지렛대로 우리나라의 낙후된 데이터 생태계를 혁신하고 기업의 경쟁력을 한 단계 제고할 수 있도록 정책적 역량을 집중하겠다 고 밝혔다.이재운  '

In [150]:
email_ptn = '[a-zA-Z0-9_\-.]+@[a-z]+(?:\.[a-z]+)+'
news_re = re.sub(email_ptn, " ", news_re)

In [151]:
news_re = re.sub("[.]+", " ", news_re)

In [152]:
news_re

'       과기정통부  22일 유영민 장관 등 참석해 기념행사2021년까지 1516억원 투입  5100여종 데이터 구축민간 클라우드 통한 외부연계체계도  개방성 강화  이데일리 이재운 기자  국가 차원의 빅데이터 활용 시대가 열린다  새로운 산업 창출과 기존 산업의 변화에 이르는  혁신성장 을 위한 센터가 문을 연다  10개 분야에 걸쳐  데이터 경제 의 발전을 위한 정부의 청사진을 현실로 구현하는데 앞장선다는 계획이다 22일 과학기술정보통신부는 서울 중구 대한상공회의소에서 데이터 생태계 조성과 혁신 성장의 기반 마련을 위한  빅데이터 플랫폼 및 센터  출범식 행사를 개최했다  유영민 과기정통부 장관을 비롯해 노웅래 국회 과학기술정보방송통신위원회 위원장 등 300여명이 참가했다  10개 분야 100개 센터 3년간 1516억원 투입이미지  픽사베이빅데이터는 데이터 활용을 통해 혁신성장을 이루자는 문재인 정부의 경제 성장 핵심 요소중 하나다  문재인 대통령이 직접 올 들어 데이터 활용과 이에 따른 정보보호 보안 에 대한 중요성을 강조하기도 했다 이런 맥락 속에서 빅데이터센터는 공공과 민간이 협업해 활용도 높은 양질의 데이터를 생산 구축하고  플랫폼은 이를 수집 분석 유통하는 역할을 담당한다  과기정통부는 분야별 플랫폼 10개소와 이와 연계된 기관별 센터 100개소를 구축하는데 3년간 총 1516억원을 투입할 계획이며  올해 우선 640억원 규모의 사업을 추진하고 있다 대상 분야는  금융 BC카드   환경 한국수자원공사   문화 한국문화정보원   교통 한국교통연구원   헬스케어 국립암센터   유통 소비 매일방송   통신 KT   중소기업 더존비즈온   지역경제 경기도청   산림 한국임업진흥원  등으로 현재 1차 공모를 통해 72개 빅데이터 센터를 선정했고  다음달 8일까지 2차 공모를 통해 28개를 추가 선정해 총 100개를 지원  운영할 계획이다  이를 통해 데이터 생태계를 혁신하고 기업의 경쟁력을 제고하는 역할을 수행한다 주요 활용 전략 사례를 보면 빅데이터 활용을 통해  신    시장 을 창출하는 방안을 담고 있다  금융 플랫폼의 경우 소상공인 신용평가 고도화 등을 통해 금융 취약 계층 대상 중금리 대출이자를 2%p 절감해 연간 1조원의 신규대출을 창출할 전망이다  유통 소비와 중소기업 플랫폼은 소상공인이나 중소기업의 폐업률 감소를  문화 플랫폼은 문화 예술 관람률과 생활체육 참여율을 높이는 방안을 모색한다  의료비 절감 헬스케어 과 기업의 매출 향상을 통한 산업 육성 통신 산림  등도 눈길을 끈다 과기정통부 제공 2021년까지 5100여종 데이터 구축 AI 알고리즘 제공도센터는 우선 분야별 데이터 부족 문제를 해소하기 위해 올해 말까지 시장 수요가 높은 1400여종 신규 데이터를 생산 구축하고  사업이 완료되는 2021년까지 총 5100여종 양질의 풍부한 데이터를 생산 구축해 시장에 공급할 계획이다 특히 공공과 민간 사이 데이터 파일형식 등이 달라 호환이 제대로 이뤄지지 못한 문제를 해소하기 위해 개방형 표준을 적용하고  품질관리기준도 마련해 운영한다 기업들이 실제 활용 가능한 최신 데이터를 확보하는데도 수개월이 소요된다는 문제점을 개선하기 위한 방안도 추진한다  센터와 플랫폼 간 연계체계에는 민간 클라우드를 기반으로 활용하고  센터에 축적된 데이터도 계속 외부와 개방 공유하며 최신 연속성을 확보한다는 계획이다 100개 센터에서 수집된 데이터를 융합 분석한 뒤 맞춤형 데이터 제작 등 양질의 데이터로 재생산하고  기업들이 필요로 하는 데이터를 원하는 형태로 즉시 활용할 수 있도록 제공할 계획이다  다양한 분석 도구는 물론 인공지능 AI  학습 알고리즘도 제공해 이용자가 보다 사용하기 편리한 환경을 제공한다 이밖에 필요한 데이터를 쉽게 등록하고 검색할 수 있도록 기준을 마련하고  데이터 보유와 관리에 대한 체계 거버넌스 를 논의하는  데이터 얼라이언스 를 구성해 보다 안전하게 이용하는 방안도 마련했다 유영민 과기정통부 장관은  오늘 출범식은 대한민국이 데이터 강국으로 가기 위한 초석을 놓은 자리 라며  세계 주요국들보다 데이터 경제로 나아가는 발걸음이 다소 늦었지만  빅데이터 플랫폼과 센터를 지렛대로 우리나라의 낙후된 데이터 생태계를 혁신하고 기업의 경쟁력을 한 단계 제고할 수 있도록 정책적 역량을 집중하겠다 고 밝혔다 이재운  '

In [153]:
news_re_fin = re.sub('[\t\s]+', " ", news_re).strip()
news_re_fin

'과기정통부 22일 유영민 장관 등 참석해 기념행사2021년까지 1516억원 투입 5100여종 데이터 구축민간 클라우드 통한 외부연계체계도 개방성 강화 이데일리 이재운 기자 국가 차원의 빅데이터 활용 시대가 열린다 새로운 산업 창출과 기존 산업의 변화에 이르는 혁신성장 을 위한 센터가 문을 연다 10개 분야에 걸쳐 데이터 경제 의 발전을 위한 정부의 청사진을 현실로 구현하는데 앞장선다는 계획이다 22일 과학기술정보통신부는 서울 중구 대한상공회의소에서 데이터 생태계 조성과 혁신 성장의 기반 마련을 위한 빅데이터 플랫폼 및 센터 출범식 행사를 개최했다 유영민 과기정통부 장관을 비롯해 노웅래 국회 과학기술정보방송통신위원회 위원장 등 300여명이 참가했다 10개 분야 100개 센터 3년간 1516억원 투입이미지 픽사베이빅데이터는 데이터 활용을 통해 혁신성장을 이루자는 문재인 정부의 경제 성장 핵심 요소중 하나다 문재인 대통령이 직접 올 들어 데이터 활용과 이에 따른 정보보호 보안 에 대한 중요성을 강조하기도 했다 이런 맥락 속에서 빅데이터센터는 공공과 민간이 협업해 활용도 높은 양질의 데이터를 생산 구축하고 플랫폼은 이를 수집 분석 유통하는 역할을 담당한다 과기정통부는 분야별 플랫폼 10개소와 이와 연계된 기관별 센터 100개소를 구축하는데 3년간 총 1516억원을 투입할 계획이며 올해 우선 640억원 규모의 사업을 추진하고 있다 대상 분야는 금융 BC카드 환경 한국수자원공사 문화 한국문화정보원 교통 한국교통연구원 헬스케어 국립암센터 유통 소비 매일방송 통신 KT 중소기업 더존비즈온 지역경제 경기도청 산림 한국임업진흥원 등으로 현재 1차 공모를 통해 72개 빅데이터 센터를 선정했고 다음달 8일까지 2차 공모를 통해 28개를 추가 선정해 총 100개를 지원 운영할 계획이다 이를 통해 데이터 생태계를 혁신하고 기업의 경쟁력을 제고하는 역할을 수행한다 주요 활용 전략 사례를 보면 빅데이터 활용을 통해 신 시장 을 창출하는 방안을 담고 있다 금융 플랫폼의 경우 소상공인 신용평가 고도화 등을 통해 금융 취약 계층 대상 중금리 대출이자를 2%p 절감해 연간 1조원의 신규대출을 창출할 전망이다 유통 소비와 중소기업 플랫폼은 소상공인이나 중소기업의 폐업률 감소를 문화 플랫폼은 문화 예술 관람률과 생활체육 참여율을 높이는 방안을 모색한다 의료비 절감 헬스케어 과 기업의 매출 향상을 통한 산업 육성 통신 산림 등도 눈길을 끈다 과기정통부 제공 2021년까지 5100여종 데이터 구축 AI 알고리즘 제공도센터는 우선 분야별 데이터 부족 문제를 해소하기 위해 올해 말까지 시장 수요가 높은 1400여종 신규 데이터를 생산 구축하고 사업이 완료되는 2021년까지 총 5100여종 양질의 풍부한 데이터를 생산 구축해 시장에 공급할 계획이다 특히 공공과 민간 사이 데이터 파일형식 등이 달라 호환이 제대로 이뤄지지 못한 문제를 해소하기 위해 개방형 표준을 적용하고 품질관리기준도 마련해 운영한다 기업들이 실제 활용 가능한 최신 데이터를 확보하는데도 수개월이 소요된다는 문제점을 개선하기 위한 방안도 추진한다 센터와 플랫폼 간 연계체계에는 민간 클라우드를 기반으로 활용하고 센터에 축적된 데이터도 계속 외부와 개방 공유하며 최신 연속성을 확보한다는 계획이다 100개 센터에서 수집된 데이터를 융합 분석한 뒤 맞춤형 데이터 제작 등 양질의 데이터로 재생산하고 기업들이 필요로 하는 데이터를 원하는 형태로 즉시 활용할 수 있도록 제공할 계획이다 다양한 분석 도구는 물론 인공지능 AI 학습 알고리즘도 제공해 이용자가 보다 사용하기 편리한 환경을 제공한다 이밖에 필요한 데이터를 쉽게 등록하고 검색할 수 있도록 기준을 마련하고 데이터 보유와 관리에 대한 체계 거버넌스 를 논의하는 데이터 얼라이언스 를 구성해 보다 안전하게 이용하는 방안도 마련했다 유영민 과기정통부 장관은 오늘 출범식은 대한민국이 데이터 강국으로 가기 위한 초석을 놓은 자리 라며 세계 주요국들보다 데이터 경제로 나아가는 발걸음이 다소 늦었지만 빅데이터 플랫폼과 센터를 지렛대로 우리나라의 낙후된 데이터 생태계를 혁신하고 기업의 경쟁력을 한 단계 제고할 수 있도록 정책적 역량을 집중하겠다 고 밝혔다 이재운'

### Processing Summary

In [131]:
def naver_news_process(raw_text):
    news = raw_text
    # 기사 본문 시작 전 잡다한 태그, 주석 등 문자열 제거
    news = news.split('_flash_removeCallback')[1]
    news = news.split('네이버 홈에서')[0]
    
    # 한글, 영어 대소문자, 숫자, @, ., %를 제외한 문자 공백으로 변환
    news_re = re.sub("[^가-힣a-zA-Z0-9@.%]", " ", news)
    
    # 기자 이메일 주소를 기준으로 신문기사 본문 endpoint 특정, 이전 부분만 가져옴
    email_ptn = '[a-zA-Z0-9_\-.]+@[a-z]+(?:\.[a-z]+)+'
    news_re = re.split(email_ptn, news_re)[0]
    
    # 연속해서 나타나는 마침표를 공백으로 대체
    news_re = re.sub("[.]+", " ", news_re)
    
    # 연속해서 나타나는 공백을 
    news_re_fin = re.sub('[\t\s]+', " ", news_re).strip()
    
    return news_re_fin

In [154]:
article_names = ["혁신성장 위한 '빅데이터센터' 출범..폐업률 낮추고 신산업 육성",
                "경기도자율주행센터 자율주행 데이터 '공공에 개방'",
                '한전, 전력데이터 활용 신서비스 개발 경진대회 공모',
                "코로나19 발생 후 인구 이동, 빅데이터로 살펴보니…"]

urls = ['https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=105&oid=018&aid=0004430108',
        'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=014&aid=0004424362',
        'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=101&oid=001&aid=0011614790',
        'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=101&oid=119&aid=0002402191']

headers = {"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"}

In [133]:
soups = [BeautifulSoup(requests.get(url, headers=headers).text, 'html.parser') for url in urls]
docs = [naver_news_process(soup.select('div._article_body_contents')[0].text) for soup in soups]

In [134]:
docs

['과기정통부 22일 유영민 장관 등 참석해 기념행사2021년까지 1516억원 투입 5100여종 데이터 구축민간 클라우드 통한 외부연계체계도 개방성 강화 이데일리 이재운 기자 국가 차원의 빅데이터 활용 시대가 열린다 새로운 산업 창출과 기존 산업의 변화에 이르는 혁신성장 을 위한 센터가 문을 연다 10개 분야에 걸쳐 데이터 경제 의 발전을 위한 정부의 청사진을 현실로 구현하는데 앞장선다는 계획이다 22일 과학기술정보통신부는 서울 중구 대한상공회의소에서 데이터 생태계 조성과 혁신 성장의 기반 마련을 위한 빅데이터 플랫폼 및 센터 출범식 행사를 개최했다 유영민 과기정통부 장관을 비롯해 노웅래 국회 과학기술정보방송통신위원회 위원장 등 300여명이 참가했다 10개 분야 100개 센터 3년간 1516억원 투입이미지 픽사베이빅데이터는 데이터 활용을 통해 혁신성장을 이루자는 문재인 정부의 경제 성장 핵심 요소중 하나다 문재인 대통령이 직접 올 들어 데이터 활용과 이에 따른 정보보호 보안 에 대한 중요성을 강조하기도 했다 이런 맥락 속에서 빅데이터센터는 공공과 민간이 협업해 활용도 높은 양질의 데이터를 생산 구축하고 플랫폼은 이를 수집 분석 유통하는 역할을 담당한다 과기정통부는 분야별 플랫폼 10개소와 이와 연계된 기관별 센터 100개소를 구축하는데 3년간 총 1516억원을 투입할 계획이며 올해 우선 640억원 규모의 사업을 추진하고 있다 대상 분야는 금융 BC카드 환경 한국수자원공사 문화 한국문화정보원 교통 한국교통연구원 헬스케어 국립암센터 유통 소비 매일방송 통신 KT 중소기업 더존비즈온 지역경제 경기도청 산림 한국임업진흥원 등으로 현재 1차 공모를 통해 72개 빅데이터 센터를 선정했고 다음달 8일까지 2차 공모를 통해 28개를 추가 선정해 총 100개를 지원 운영할 계획이다 이를 통해 데이터 생태계를 혁신하고 기업의 경쟁력을 제고하는 역할을 수행한다 주요 활용 전략 사례를 보면 빅데이터 활용을 통해 신 시장 을 창출하는 방안을 담고 있다 금융 플랫폼의 경우 소상공인 신용평가 고도화 등을 통해 금융 취약 계층 대상 중금리 대출이자를 2%p 절감해 연간 1조원의 신규대출을 창출할 전망이다 유통 소비와 중소기업 플랫폼은 소상공인이나 중소기업의 폐업률 감소를 문화 플랫폼은 문화 예술 관람률과 생활체육 참여율을 높이는 방안을 모색한다 의료비 절감 헬스케어 과 기업의 매출 향상을 통한 산업 육성 통신 산림 등도 눈길을 끈다 과기정통부 제공 2021년까지 5100여종 데이터 구축 AI 알고리즘 제공도센터는 우선 분야별 데이터 부족 문제를 해소하기 위해 올해 말까지 시장 수요가 높은 1400여종 신규 데이터를 생산 구축하고 사업이 완료되는 2021년까지 총 5100여종 양질의 풍부한 데이터를 생산 구축해 시장에 공급할 계획이다 특히 공공과 민간 사이 데이터 파일형식 등이 달라 호환이 제대로 이뤄지지 못한 문제를 해소하기 위해 개방형 표준을 적용하고 품질관리기준도 마련해 운영한다 기업들이 실제 활용 가능한 최신 데이터를 확보하는데도 수개월이 소요된다는 문제점을 개선하기 위한 방안도 추진한다 센터와 플랫폼 간 연계체계에는 민간 클라우드를 기반으로 활용하고 센터에 축적된 데이터도 계속 외부와 개방 공유하며 최신 연속성을 확보한다는 계획이다 100개 센터에서 수집된 데이터를 융합 분석한 뒤 맞춤형 데이터 제작 등 양질의 데이터로 재생산하고 기업들이 필요로 하는 데이터를 원하는 형태로 즉시 활용할 수 있도록 제공할 계획이다 다양한 분석 도구는 물론 인공지능 AI 학습 알고리즘도 제공해 이용자가 보다 사용하기 편리한 환경을 제공한다 이밖에 필요한 데이터를 쉽게 등록하고 검색할 수 있도록 기준을 마련하고 데이터 보유와 관리에 대한 체계 거버넌스 를 논의하는 데이터 얼라이언스 를 구성해 보다 안전하게 이용하는 방안도 마련했다 유영민 과기정통부 장관은 오늘 출범식은 대한민국이 데이터 강국으로 가기 위한 초석을 놓은 자리 라며 세계 주요국들보다 데이터 경제로 나아가는 발걸음이 다소 늦었지만 빅데이터 플랫폼과 센터를 지렛대로 우리나라의 낙후된 데이터 생태계를 혁신하고 기업의 경쟁력을 한 단계 제고할 수 있도록 정책적 역량을 집중하겠다 고 밝혔다 이재운',
 '판교 자율주행 실증단지 자율주행 데이터 개방 사업 선정 파이낸셜뉴스 수원 장충식 기자 경기도는 경기도 자율주행센터에서 수집되는 자율주행 관련 데이터를 공공에 개방한다고 14일 밝혔다 이는 정부의 2020년 국가중점 데이터 개방 지원 사업에 경기도 자율주행센터의 판교 자율주행 실증단지 자율주행 데이터가 선정된 데 따른 조치로 오는 6월부터 경기도 자율주행센터 자율주행 데이터 개방 사업 이 추진될 예정이다 이에 따라 누구나 공공데이터포털 및 경기도자율주행센터포털에 접속하면 판교 자율주행 실증단지에서 수집되는 자율주행 관련 데이터를 별도의 데이터 가공 처리 없이 편리하게 활용할 수 있게 된다 올 하반기부터 2022년까지 3개년에 걸쳐 자율주행 산업 발전에 필요한 데이터가 공공에 개방될 예정으로 자율주행 산업 활성화에 기여할 것으로 도는 기대하고 있다 임문영 경기도 미래성장정책관은 경기도 자율주행센터는 작년 개소 이후 건강하고 발전적인 자율주행 생태계 조성을 위해 힘써오고 있다 며 센터는 앞으로도 경기도의 선진화된 자율주행기술 및 방대한 양의 데이터를 활용해 국내 자율주행 기술 발전에 앞장설 것 이라고 말했다 한편 경기도는 차세대융합기술연구원과 함께 자율주행 분야 산업생태계를 구축하기 위해 지난해 5월 경기도 자율주행센터를 출범했다 운전자 없이 주행이 가능한 자율주행 레벨4 수준의 자율주행차 제로셔틀 개발과 스타트업의 실증 테스트 및 빅데이터 서비스 등을 지원하는 등 자율주행 분야의 세계적인 실증단지 구축 및 운영을 위해 꾸준한 지원을 이어가고 있다',
 '한국전력공사 한국전력공사 제공 나주 연합뉴스 송형일 기자 한국전력은 전력 데이터를 활용한 신 서비스 개발 경진대회가 8월 20일 한전 아트센터에서 개최된다고 18일 밝혔다 산업통상자원부가 주최하고 한전과 전력그룹사 광주과학기술원이 주관하는 이번 행사는 전력 빅데이터를 활용하는 새로운 사업 모델 발굴을 위해 마련됐다 대회 참가를 희망하는 학생 일반인 벤처기업과 새싹기업은 경진대회 홈페이지 http contest kepco co kr 에서 18일부터 6월 17일까지 제안서를 내면 된다 1차 서류심사를 통과한 팀이나 개인은 제공된 전력 데이터를 활용해 서비스를 개발하고 데이터가 외부 반출이 불가한 경우에는 한전 아트센터에 마련된 데이터 공유센터에서 개발한다 완성도 기술성 상용화 가능성 확장성 등을 기준으로 사내 직원과 사외 전문위원이 함께 평가한다 시상은 개인 학생 일반인 과 기업 2개의 부문으로 나눠서 진행한다 최종 선정 팀에는 총 2천150만 원의 상금을 주며 수상작의 서비스 솔루션은 에너지마켓플레이스 EN TER 에 등록해 사업화 할 수 있는 기회를 제공한다 김종갑 한전 사장은 한전의 전력 데이터와 다른 공공기관 및 민간의 데이터를 융합해 보다 가치 있는 대국민 편익서비스를 많이 만들어 내길 기대한다 고 말했다',
 '통계청 SK텔레콤 모바일 빅데이터 분석 5월 들어 회복세 코로나19 발생 후 4주차 20대 미만 큰 폭 감소돼코로나19 발생 후 인구 이동을 분석한 결과 발생 후 4주차 토요일인 2월 29일 3월 1일 가장 큰 폭으로 감소했으며 이후 감소폭이 점차 완화돼 5월 첫째 주를 기해 전년 대비 약 83%로 상당 수준 회복된 것으로 나타났다 인구 이동은 사람 간 접촉 가능성이 상대적으로 높은 상업지역 관광지 레저스포츠시설이 대형아울렛이나 주거지역보다 이동량 감소가 큰 편이었으나 5월 초 4일 연휴를 기점으로 관광지와 레저스포츠시설에서 큰 폭으로 늘어난 것으로 파악됐다 이 같은 이동결과는 통계청과 SK텔레콤이 모바일 빅데이터를 기반으로 전국 SKT 가입자의 주중과 주말 인구 이동 정보를 이용해 추정한 결과다 코로나19 발생 전후 인구 이동 통계청코로나19 발생 전후 대비 통계청통계청과 SK텔레콤 시장점유율 약 42% 은 지난해 5월 업무협약을 체결한 이후 정부혁신의 일환으로 공공 민간 협업을 추진하고 있으며 통계데이터센터 홈페이지를 통해 모바일 유동인구 지도를 서비스 중이다 분석은 성 연령별 입지유형별 17개 시도별로 주중과 주말의 인구 이동 변화를 다각적으로 작년 같은 시기와 비교했으며 인구 이동은 시 군 구 간 이동을 의미하며 본인이 실거주하는 시 군 구 외 타 시 군 구 행정동 를 30분 이상 방문한 경우를 이동 건수로 집계한 것이다 통계청은 인구 이동량을 등록센서스 인구를 모수로 성과 연령 5세별 지역 읍 면 동 별 가중치를 적용 추정해본 결과 코로나19 지역 집단감염 2월20일 29일 영향으로 발생 후 4주차 토요일 2월29일 인구 이동량은 작년 같은 주 토요일 대비 가장 큰 폭 41 9% 으로 감소한 이후 3월부터 감소폭은 점차 완화됐다고 설명했다 이어 발생 후 13주차 토요일인 5월 2일에 상당 수준 회복 약 83% 됐다가 발생 후 14주차 토요일인 5월 9일에는 회복세가 주춤 약 75% 한 것으로 집계됐다 이는 13주차 4일간 연휴 4월30일 5월3일 기간에 일시 이동량이 크게 늘어난 것으로 보였으며 특히 연휴가 낀 주말에 코로나19로 인한 인구 이동량 변동이 크게 나타났다 성별 연령별로는 전반적으로 남성보다 여성이 연령별로는 20세 미만 20대 60대 70세 이상에서 이동량 감소가 큰 편이었다 다만 13주차인 4월 27일 5월 3일에는 4일간 연휴에 따른 가족 동반 이동이 늘어 여성과 20세 미만의 이동량이 큰 폭으로 늘었다 코로나19 발생 후 입지유형별 이동 통계청입지유형별로는 레저스포츠시설이 대형아울렛 주거지역보다 이동량 감소가 큰 편이었으며 연휴기간에는 관광지 레저스포츠시설에서 큰 폭의 증가세를 보였다 입지분류로는 상업지역 관광지 대형아울렛 사무지역 레저 스포츠시설 주거지역 등 6개로 한정했다 시 도별 이동으로는 코로나19 발생 후 제주 강원 부산 대구 등 관광지역이나 대규모 확진자 발생지역을 중심으로 인구 유입이 감소했고 13주차에는 4일간 연로 전남 전북 충남 강원 등 대도시가 아닌 지역으로 인구 유입이 큰 폭으로 늘어났다 통계청은 앞으로도 각종 사회 경제적 이슈 발생될 때 모바일 빅데이터를 활용해 정부정책에 참고할 수 있는 다양한 기초자료를 제공한다는 방침이다 데일리안 이소희 기자']

In [135]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
import numpy as np
# smooth -> False
tfidf_vectorizer = TfidfVectorizer(smooth_idf=True)
tfidf = tfidf_vectorizer.fit_transform(docs)

res_df = pd.DataFrame(tfidf.todense(),
             columns=tfidf_vectorizer.get_feature_names())
res_df

,100개,100개를,100개소를,10개,10개소와,13주차,13주차에는,13주차인,1400여종,14일,...,활용하는,활용한,활용할,활용해,회복,회복된,회복세,회복세가,희망하는,힘써오고
0,0.072021,0.036011,0.036011,0.072021,0.036011,0.000000,0.000000,0.000000,0.036011,0.000000,...,0.000000,0.000000,0.028391,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.048265,...,0.000000,0.000000,0.038053,0.030807,0.000000,0.000000,0.000000,0.000000,0.000000,0.048265
2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.079417,0.079417,0.000000,0.050691,0.000000,0.000000,0.000000,0.000000,0.079417,0.000000
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.072905,0.036452,0.036452,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.023267,0.036452,0.036452,0.036452,0.036452,0.000000,0.000000

In [201]:
argmax_index = np.array(tfidf.todense().argmax(axis=1)).flatten()
print(argmax_index)
res_df.iloc[:, argmax_index]

[252 566 586 551]

        데이터      자율주행        전력        인구
0  0.344776  0.000000  0.000000  0.000000
1  0.123228  0.723979  0.000000  0.000000
2  0.050691  0.000000  0.317669  0.000000
3  0.000000  0.000000  0.000000  0.400975

In [231]:
for i in range(4):
    print(article_names[i])
    print(res_df.T[i].sort_values(ascending=False)[:3])
    print('---')

혁신성장 위한 '빅데이터센터' 출범..폐업률 낮추고 신산업 육성
데이터     0.344776
계획이다    0.180053
위한      0.180053
Name: 0, dtype: float64
---
경기도자율주행센터 자율주행 데이터 '공공에 개방'
자율주행    0.723979
경기도     0.289592
판교      0.144796
Name: 1, dtype: float64
---
한전, 전력데이터 활용 신서비스 개발 경진대회 공모
전력    0.317669
한전    0.238252
학생    0.158835
Name: 2, dtype: float64
---
코로나19 발생 후 인구 이동, 빅데이터로 살펴보니…
인구    0.400975
발생    0.364523
5월    0.201176
Name: 3, dtype: float64
---

In [140]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer

count_vectorizer = CountVectorizer()
DTM = count_vectorizer.fit_transform(docs)
#DTM.data

In [141]:
tfidf_transformer = TfidfTransformer()
tfidf = tfidf_transformer.fit_transform(DTM)
tfidf.todense()

matrix([[0.07202106, 0.03601053, 0.03601053, ..., 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.04826527],
        [0.        , 0.        , 0.        , ..., 0.        , 0.07941732,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.03645232, 0.        ,
         0.        ]])

In [142]:
pd.DataFrame(tfidf.todense(), columns=tfidf_vectorizer.get_feature_names())

,100개,100개를,100개소를,10개,10개소와,13주차,13주차에는,13주차인,1400여종,14일,...,활용하는,활용한,활용할,활용해,회복,회복된,회복세,회복세가,희망하는,힘써오고
0,0.072021,0.036011,0.036011,0.072021,0.036011,0.000000,0.000000,0.000000,0.036011,0.000000,...,0.000000,0.000000,0.028391,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.048265,...,0.000000,0.000000,0.038053,0.030807,0.000000,0.000000,0.000000,0.000000,0.000000,0.048265
2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.079417,0.079417,0.000000,0.050691,0.000000,0.000000,0.000000,0.000000,0.079417,0.000000
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.072905,0.036452,0.036452,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.023267,0.036452,0.036452,0.036452,0.036452,0.000000,0.000000

In [174]:
from konlpy.tag import Mecab
mecab = Mecab()
mecab_docs = [mecab.pos(doc, flatten=True) for doc in docs]

In [198]:
mecab_docs_nnp_nng = [[token[0] for token in mecab_docs[i] if token[1] in ['NNG', 'NNP']] for i in range(4)]

In [199]:
mecab_docs_nnp_nng_joined = [' '.join(mecab_doc) for mecab_doc in mecab_docs_nnp_nng]
mecab_docs_nnp_nng_joined

['과기 정통부 유영민 장관 참석 기념행사 투입 여종 데이터 구축 민간 클라우드 외부 연계 체계 개방 강화 데일리 이재운 기자 국가 차원 빅 데이터 활용 시대 산업 창출 기존 산업 변화 혁신 장 센터 문 분야 데이터 경제 발전 정부 청사진 현실 구현 계획 과학 기술 정보 통신부 서울 중구 대한 상공 회의소 데이터 생태 조성 혁신 성장 기반 마련 빅 데이터 플랫 폼 센터 출범식 행사 개최 유영민 과기 정통부 장관 노웅래 국회 과학 기술 정보 방송 통신 위원회 위원장 참가 분야 센터 간 투입 이미지 픽사 베이 빅 데이터 데이터 활용 혁신 장 문재 정부 경제 성장 핵심 요소 하나다 문재인 대통령 데이터 활용 정보 보호 보안 중요 강조 맥락 속 빅 데이터 센터 공공 민간 협업 활용 양질 데이터 생산 구축 플랫 폼 수집 분석 유통 역할 담당 과기 정통부 분야 플랫 폼 연계 기관 센터 구축 투입 계획 올해 규모 사업 추진 대상 분야 금융 카드 환경 한국 수자원 공사 문화 한국 문화 정보원 교통 한국 교통 연구원 헬스 국립암센터 유통 소비 방송 통신 중소기업 비즈 지역 경제 경기 도청 산림 한국 임업 흥원 공모 빅 데이터 센터 선정 다음 달 공모 추가 선정 지원 운영 계획 데이터 생태계 혁신 기업 경쟁력 제고 역할 수행 주요 활용 전략 사례 빅 데이터 활용 시장 창출 방안 금융 플랫 폼 경우 소 상공 신용 평가 고도 금융 취약 계층 대상 금리 대출 절감 연간 신규 대출 창출 전망 유통 소비 중소기업 플랫 폼 소상 공인 중소기업 폐업 감소 문화 플랫 폼 문화 예술 관람 생활 체육 참여 방안 모색 의료비 절감 헬스 케어 과 기업 매출 향상 산업 육성 통신 산림 눈길 과기 정통부 제공 여종 데이터 구축 알고리즘 제공 센터 분야 데이터 부족 문제 해소 올해 시장 수요 여종 신규 데이터 생산 구축 사업 완료 여종 양질 데이터 생산 구축 시장 공급 계획 공공 민간 사이 데이터 파일 형식 호환 문제 해소 개방 표준 적용 품질 관리 기준 마련 운영 기업 실제 활용 가능 최신 데이터 확보 수개월 소요 문제점 개선 방안 추진 센터 플랫폼 연계 체계 민간 클라우드 기반 활용 센터 축적 데이터 외부 개방 공유 최신 연속 확보 계획 센터 수집 데이터 융합 분석 뒤 맞춤 데이터 제작 양질 데이터 생산 기업 필요 데이터 형태 활용 제공 계획 분석 도구 인공지능 학습 알고리즘 제공 이용자 사용 편리 환경 제공 밖 필요 데이터 등록 검색 기준 마련 데이터 보유 관리 체계 거버넌스 논의 데이터 얼라이언스 구성 이용 방안 마련 유영민 과기 정통부 장관 출범식 대한민국 데이터 강국 초석 자리 세계 주요 국 데이터 경제 발걸음 빅 데이터 플랫 폼 센터 지렛대 우리나라 낙후 데이터 생태계 혁신 기업 경쟁력 단계 제고 정책 역량 집중 고 이재운',
 '판교 자율 주행 실증 자율 주행 데이터 개방 사업 선정 파이낸셜 뉴스 수원 장충식 기자 경기도 경기도 자율 주행 센터 수집 자율 주행 관련 데이터 공공 개방 정부 국가 중점 데이터 개방 지원 사업 경기도 자율 주행 센터 판교 자율 주행 실증 자율 주행 데이터 선정 조치 경기도 자율 주행 센터 자율 주행 데이터 개방 사업 추진 예정 공공 데이터 포털 경기도 자율 주행 센터 포털 접속 판교 자율 주행 실증 단지 수집 자율 주행 관련 데이터 별도 데이터 가공 처리 편리 활용 하반기 자율 주행 산업 발전 필요 데이터 공공 개방 예정 자율 주행 산업 활성 기여 기대 임문영 경기도 미래 장정 책 관 경기도 자율 주행 센터 작년 개소 이후 건강 발전 자율 주행 생태 조성 센터 앞 경기도 선진 자율 주행 기술 양 데이터 활용 국내 자율 주행 기술 발전 말 경기도 차세대 융합 기술 연구원 자율 주행 분야 산업 생태계 구축 지난해 경기도 자율 주행 센터 출범 운전자 주행 가능 자율 주행 레벨 수준 자율 주행 차 셔틀 개발 스타트업 실증 테스트 빅 데이터 서비스 지원 자율 주행 분야 세계 실증 구축 운영 지원',
 '한국전력공사 한국전력공사 제공 나주 연합뉴스 송 형 기자 한국전력 전력 데이터 활용 서비스 개발 경진 대회 한전 아트 센터 개최 산업 통상 자원 부 주최 한전 전력 그룹 광주 과학 기술원 주관 이번 행사 전력 빅 데이터 활용 사업 모델 발굴 마련 대회 참가 희망 학생 일반 벤처 기업 새싹 기업 경진 대회 홈페이지 제안서 서류 심사 통과 팀 개인 제공 전력 데이터 활용 서비스 개발 데이터 외부 반출 불가 경우 한전 아트 센터 마련 데이터 공유 센터 개발 완성 기술 상용 가능 확장 기준 사내 직원 사외 전문 위원 평가 시상 개인 학생 일반 과 기업 부문 진행 최종 선정 팀 상금 수 상작 서비스 솔루션 에너지 마켓 플레이스 등록 사업 기회 제공 김종갑 한전 사장 한전 전력 데이터 공공 기관 민간 데이터 융합 가치 대국민 편익 서비스 기대 말',
 '통계청 텔레콤 모바일 빅 데이터 분석 회복세 코로나 발생 후 미만 폭 감소 코로나 발생 후 인구 이동 분석 결과 발생 후 토요일 폭 감소 이후 감소 폭 완화 전년 대비 상당 수준 회복 인구 이동은 사람 접촉 가능 상대 상업 지역 관광지 레저 스포츠 시설 대형 아울렛 주거 지역 동량 감소 연휴 기점 관광지 레저 스포츠 시설 폭 파악 이동결 통계청 텔레콤 모바일 빅 데이터 기반 전국 가입자 주중 주말 인구 이동 정보 이용 추정 결과 코로나 발생 전후 인구 이동 통계청 코로나 발생 전후 대비 통계청 통계청 텔레콤 시장 점유 은 지난해 업무 협약 체결 이후 정부 혁신 일환 공공 민간 협업 추진 통계 데이터 센터 홈페이지 모바일 유동 인구 지도 서비스 분석 성 연령 입지 유형 시도 주중 주말 인구 이동 변화 다각 작년 시기 비교 인구 이동은 시 군 구 이동 의미 본인 실거 주 시 군 구 행정 동 이상 방문 경우 이동 건수 집계 통계청 인구 동량 등록 센서스 인구 모수 성과 연령 세별 지역 읍 면 동 별 가중치 적용 추정 결과 코로나 지역 집단 감염 영향 발생 후 토요일 인구 동량 작년 주 토요일 대비 폭 감소 이후 감소 폭 완화 설명 발생 후 토요일 상당 수준 회복 발생 후 토요일 회복세 집계 간 연휴 기간 동량 연휴 주말 코로나 인구 동량 변동 성별 연령 전반 남성 여성 연령 미만 이상 동량 감소 간 연휴 가족 동반 이동 여성 미만 동량 폭 코로나 발생 후 입지 유형 이동 통계청 입지 유형 레저 스포츠 시설 대형 아울렛 주거 지역 동량 감소 연휴 기간 관광지 레저 스포츠 시설 폭 증가세 입지 분류 상업 지역 관광지 대형 아울렛 사무 지역 레저 스포츠 시설 주거 지역 한정 시 도 이동 코로나 발생 후 제주 강원 부산 대구 관광 지역 규모 확진 발생 지역 중심 인구 유입 감소 간 연 전남 전북 충남 강원 도시 지역 인구 유입 폭 통계청 앞 각종 사회 경제 이슈 발생 때 모바일 빅 데이터 활용 정부 정책 참고 기초 자료 제공 방침 데일리안 이소희 기자']

In [204]:
# smooth -> False
tfidf_vectorizer = TfidfVectorizer(smooth_idf=True)
tfidf_mecab = tfidf_vectorizer.fit_transform(mecab_docs_nnp_nng_joined)

res_df2 = pd.DataFrame(tfidf_mecab.todense(),
             columns=tfidf_vectorizer.get_feature_names())

In [233]:
res_df2

,가공,가능,가입자,가족,가중치,가치,각종,감소,감염,강국,...,확장,확진,환경,활성,활용,회복,회복세,회의소,흥원,희망
0,0.00000,0.016269,0.00000,0.00000,0.00000,0.000000,0.00000,0.024579,0.00000,0.031175,...,0.000000,0.00000,0.062351,0.00000,0.146417,0.000000,0.000000,0.031175,0.031175,0.000000
1,0.02685,0.014011,0.00000,0.00000,0.00000,0.000000,0.00000,0.000000,0.00000,0.000000,...,0.000000,0.00000,0.000000,0.02685,0.028023,0.000000,0.000000,0.000000,0.000000,0.000000
2,0.00000,0.038550,0.00000,0.00000,0.00000,0.073873,0.00000,0.000000,0.00000,0.000000,...,0.073873,0.00000,0.000000,0.00000,0.115651,0.000000,0.000000,0.000000,0.000000,0.073873
3,0.00000,0.015452,0.02961,0.02961,0.02961,0.000000,0.02961,0.210102,0.02961,0.000000,...,0.000000,0.02961,0.000000,0.00000,0.015452,0.059219,0.059219,0.000000,0.000000,0.000000

In [203]:
argmax_index2 = np.array(tfidf_mecab.todense().argmax(axis=1)).flatten()
print(argmax_index2)
res_df2.iloc[:, argmax_index2]

[ 97 317 289 270]

        데이터        주행        전력        인구
0  0.504326  0.000000  0.000000  0.000000
1  0.154124  0.644391  0.000000  0.000000
2  0.269851  0.000000  0.369367  0.000000
3  0.061806  0.000000  0.000000  0.384926

In [230]:
for i in range(4):
    print(article_names[i])
    print(res_df2.T[i].sort_values(ascending=False)[:3])
    print('---')

혁신성장 위한 '빅데이터센터' 출범..폐업률 낮추고 신산업 육성
데이터    0.504326
플랫     0.218227
계획     0.187052
Name: 0, dtype: float64
---
경기도자율주행센터 자율주행 데이터 '공공에 개방'
주행     0.644391
자율     0.617542
경기도    0.268496
Name: 1, dtype: float64
---
한전, 전력데이터 활용 신서비스 개발 경진대회 공모
전력     0.369367
한전     0.369367
데이터    0.269851
Name: 2, dtype: float64
---
코로나19 발생 후 인구 이동, 빅데이터로 살펴보니…
인구    0.384926
발생    0.355316
이동    0.266487
Name: 3, dtype: float64
---

# [비교] re 전처리 vs. mecab postagger

In [227]:
concat = pd.concat([res_df.iloc[:, argmax_index] ,res_df2.iloc[:, argmax_index2]],
          names=[col1+'_re' for col1 in res_df.iloc[:, argmax_index].columns.tolist()]+\
                  [col2+'_mecab' for col2 in res_df2.iloc[:, argmax_index2].columns.tolist()]
          , axis=1)
concat

,데이터,자율주행,전력,인구,데이터,주행,전력,인구
0,0.344776,0.000000,0.000000,0.000000,0.504326,0.000000,0.000000,0.000000
1,0.123228,0.723979,0.000000,0.000000,0.154124,0.644391,0.000000,0.000000
2,0.050691,0.000000,0.317669,0.000000,0.269851,0.000000,0.369367,0.000000
3,0.000000,0.000000,0.000000,0.400975,0.061806,0.000000,0.000000,0.384926